//////////////////////////////////////////////////////////////
//Do not change these pin assignments they are perminant 
//locations on the MicroBot development board.
//you may define extra pins not allready defined.
//////////////////////////////////////////////////////////////
#define _TRIG 28
#define _ECHO 27

#define _DCS0 26
#define _DCS1 25
#define _DCS2 24
#define _DCS3 23

#define _SW1  31
#define _SW2  1
#define _SW3  2
#define _SW4  9

#define BT_KEY  10
#define BT_PWR  11
//////////////////////////////////////////////////////////////
//End manditory pin assignments
//////////////////////////////////////////////////////////////
